ERROR 2025-04-16 14:55:42,704 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 14:55:45,581 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO 2025-04-16 14:55:57,756 Info -cls=create_admin_login|args=()|kwargs={'username': 'monicaigun', 'password': 'pass123!'}|Result={"code":200,"data":{"email":"monicaigun@gmail.com","id":"202504-1119-5020-0e41c8ad-e9c4-40f0-8918-463976992b28","password":[{"password":"gAAAAABn-RAMonam5aSQyZXmaNlAa4w12ICQqYlgiEOepgAB2Din2JVZxp-mPeHutsRMqbi01wXjfwva4OCKxIQmBA8c1uVNWw==","primary":false},{"password":"gAAAAABn-RParMu5nUECh_rO9adD07qt3WFDidYCGh1shH2uzcu7lc04M5VGd9ZIsMomp_4XmO1Qt4bwY1cZYZQWcACY60DC4g==","primary":true}],"role":"admin","username":"monicaigun"},"message":"Successfully Login"}
-
ERROR 2025-04-16 15:33:14,888 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:41:54,036 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:42:22,510 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:43:27,304 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:43:45,718 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:44:02,681 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:44:31,755 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 15:45:24,522 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:04:48,507 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:05:55,234 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:06:09,140 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:07:05,921 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:08:12,018 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:09:29,612 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:10:48,087 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    if json.loads(request.data) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:11:41,396 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 61, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:16:40,859 Error -cls=create_get_device_admin|Result=index out of range|Exception=IndexError('index out of range')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    if request.data[0] == None:
       ~~~~~~~~~~~~^^^
IndexError: index out of range
ERROR 2025-04-16 20:19:44,497 Error -cls=create_get_device_admin|Result=415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.|Exception=<UnsupportedMediaType '415: Unsupported Media Type'>- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    if request.json == None:
    ^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 560, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\flask\wrappers.py", line 214, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
ERROR 2025-04-16 20:20:26,522 Error -cls=create_get_device_admin|Result=415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.|Exception=<UnsupportedMediaType '415: Unsupported Media Type'>- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 58, in wrapper
    if request.json is None:
    ^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 560, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\flask\wrappers.py", line 214, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
ERROR 2025-04-16 20:23:11,449 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 61, in wrapper
    kwargs_params = json.loads(request.data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR 2025-04-16 20:23:24,665 Error -cls=create_get_device_admin|Result=Expecting value: line 1 column 1 (char 0)|Exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 61, in wrapper
    #         kwargs_params = json.loads(request.data)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-04-16 20:23:53,374 Info -cls=create_get_device_admin|args=()|kwargs=None|Result={"code":401,"message":"A valid username authorize is missing!"}
-
ERROR 2025-04-16 20:24:22,672 Error -cls=create_get_device_admin|Result=415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.|Exception=<UnsupportedMediaType '415: Unsupported Media Type'>- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 50, in create_get_device_admin
    hjhjh = request.json()
            ^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 560, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\flask\wrappers.py", line 214, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\envV1\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
WARNING 2025-04-16 20:27:24,537 Info -cls=create_get_device_admin|args=()|kwargs={}|Result={"code":401,"message":"A valid username authorize is missing!"}
-
ERROR 2025-04-16 20:27:51,750 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
ERROR 2025-04-16 20:30:08,267 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
WARNING 2025-04-16 20:30:15,225 Info -cls=create_get_device_admin|args=()|kwargs={}|Result={"code":401,"message":"A valid username authorize is missing!"}
-
ERROR 2025-04-16 20:30:24,726 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
ERROR 2025-04-16 20:30:56,828 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
ERROR 2025-04-16 20:30:58,957 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
ERROR 2025-04-16 20:37:19,543 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
ERROR 2025-04-16 20:37:33,547 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 64, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
ERROR 2025-04-16 20:39:13,582 Error -cls=create_get_device_admin|Result=c_get_device_admin() got multiple values for argument 'current_user'|Exception=TypeError("c_get_device_admin() got multiple values for argument 'current_user'")- 
Traceback (most recent call last):
  File "D:\iot\backend\v1\decorators\silvia_log.py", line 72, in wrapper
    results_function = func(*args,**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\test_auth.py", line 51, in create_get_device_admin
    get_deviceList = c_get_device_admin(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iot\backend\v1\decorators\middleware.py", line 52, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: c_get_device_admin() got multiple values for argument 'current_user'
